export function computeStyles(theme: any, styleMap: any): any;
export function attachStyler(themeService: any, styleMap: any, widgetOrCallback: any): any;
export function attachBadgeStyler(widget: any, themeService: any, style: any): any;
export function attachQuickOpenStyler(widget: any, themeService: any, style: any): any;
export function attachListStyler(widget: any, themeService: any, overrides: any): any;
export function attachMenuStyler(widget: any, themeService: any, style: any): any;
export namespace defaultListStyles {
    export { listFocusBackground };
    export { listFocusForeground };
    export const listActiveSelectionBackground: (theme: any) => any;
    export { listActiveSelectionForeground };
    export { listActiveSelectionBackground as listFocusAndSelectionBackground };
    export { listActiveSelectionForeground as listFocusAndSelectionForeground };
    export { listInactiveSelectionBackground };
    export { listInactiveSelectionForeground };
    export { listInactiveFocusBackground };
    export { listHoverBackground };
    export { listHoverForeground };
    export { listDropBackground };
    export { activeContrastBorder as listFocusOutline };
    export { activeContrastBorder as listSelectionOutline };
    export { activeContrastBorder as listHoverOutline };
    export { listFilterWidgetBackground };
    export { listFilterWidgetOutline };
    export { listFilterWidgetNoMatchesOutline };
    export { widgetShadow as listMatchesShadow };
    export { treeIndentGuidesStroke };
}
export namespace defaultMenuStyles {
    export { widgetShadow as shadowColor };
    export { menuBorder as borderColor };
    export { menuForeground as foregroundColor };
    export { menuBackground as backgroundColor };
    export { menuSelectionForeground as selectionForegroundColor };
    export { menuSelectionBackground as selectionBackgroundColor };
    export { menuSelectionBorder as selectionBorderColor };
    export { menuSeparatorBackground as separatorColor };
}
import { listFocusBackground } from "./colorRegistry.js";
import { listFocusForeground } from "./colorRegistry.js";
import { listActiveSelectionForeground } from "./colorRegistry.js";
import { listActiveSelectionBackground as listActiveSelectionBackground_1 } from "./colorRegistry.js";
import { listInactiveSelectionBackground } from "./colorRegistry.js";
import { listInactiveSelectionForeground } from "./colorRegistry.js";
import { listInactiveFocusBackground } from "./colorRegistry.js";
import { listHoverBackground } from "./colorRegistry.js";
import { listHoverForeground } from "./colorRegistry.js";
import { listDropBackground } from "./colorRegistry.js";
import { activeContrastBorder } from "./colorRegistry.js";
import { listFilterWidgetBackground } from "./colorRegistry.js";
import { listFilterWidgetOutline } from "./colorRegistry.js";
import { listFilterWidgetNoMatchesOutline } from "./colorRegistry.js";
import { widgetShadow } from "./colorRegistry.js";
import { treeIndentGuidesStroke } from "./colorRegistry.js";
import { menuBorder } from "./colorRegistry.js";
import { menuForeground } from "./colorRegistry.js";
import { menuBackground } from "./colorRegistry.js";
import { menuSelectionForeground } from "./colorRegistry.js";
import { menuSelectionBackground } from "./colorRegistry.js";
import { menuSelectionBorder } from "./colorRegistry.js";
import { menuSeparatorBackground } from "./colorRegistry.js";
