export const isWindows: boolean;
export const isMacintosh: boolean;
export const isLinux: boolean;
export const isNative: boolean;
export const isWeb: boolean;
export const isIOS: boolean;
export const globals: {};
export const setImmediate: any;
export const OS: number;
